export const clientThemeMock = {
  id: "68c8cd66-e629-465b-a7d5-c0c65e543309",
  time_to_reload_pages: null,
  ga4_id: null,
  twitter_id: null,
  facebook_id: null,
  instagram_id: null,
  logoCollection: {
    logos: [
      {
        isPrimaryLogo: true,
        url: "https://erikatomato.local.api.umbrielcms.com.br:3001/uploads/cfe7e429ed39fa89c1b6-Free Logo Design (1).png?width=200&height=200",
        isWhiteTheme: true,
      },
    ],
  },
  colors: [
    "#ffffff",
    "#fafafa",
    "#19191b",
    "#3f51b5",
    "#03a9f4",
    "#8bc34a",
    "#ffeb3b",
    "#ff5722",
  ],
  site_name: "Erika's Blog",
  api_key: "a5942128e38b2de50ef3cab6308449ef31741fa884153cb7442313ff3e7c30ba",
  darkMode: null,
  tenant_id: "b2c2bfed-aa2a-40d6-95e3-8376022db45c",
  fontMapping: {
    articleTitle: "Inter",
    articleSubtitle: "Inter",
    articleBody: "Inter",
    headerTitle: "Inter",
    headerText: "Inter",
  },
  colorMapping: {
    light: {
      articleBackground: "#3f51b5",
      articleTitle: "#FFFFFF",
      articleSubtitle: "#FFFFFF",
      articleText: "#FFFFFF",
      headerBackground: "#3f51b5",
      headerText: "#FFFFFF",
      primaryButton: "#fafafa",
      secondaryButton: "#fafafa",
      accent: "#fafafa",
      sidebarBackground: "#3f51b5",
      sidebarText: "#FFFFFF",
    },
    dark: {
      articleBackground: "#19191b",
      articleTitle: "#ffffff",
      articleSubtitle: "#ffffff",
      articleText: "#ffffff",
      headerBackground: "#19191b",
      headerText: "#ffffff",
      primaryButton: "#fafafa",
      secondaryButton: "#ffffff",
      accent: "#19191b",
      sidebarBackground: "#19191b",
      sidebarText: "#FFFFFF",
    },
  },
  websiteSizes: {
    desktop: {
      siteContainerWidth: "100%",
      articleContainerWidth: "80%",
      headerHeight: "80px",
      footerHeight: "60px",
      siteContainerMaxWidth: "1150px",
      articleContainerMaxWidth: "1200px",
    },
    mobile: {
      siteContainerWidth: "100%",
      articleContainerWidth: "95%",
      headerHeight: "60px",
      footerHeight: "50px",
      siteContainerMaxWidth: "100%",
      articleContainerMaxWidth: "100%",
    },
    tablet: {
      siteContainerWidth: "100%",
      articleContainerWidth: "90%",
      headerHeight: "70px",
      footerHeight: "55px",
      siteContainerMaxWidth: "1024px",
      articleContainerMaxWidth: "800px",
    },
  },
};
