import '../index.css'
export { default as Theme } from '../styles/index'
export { default as CustomThemeProvider } from '../styles/index'
export { default as SideMenu } from './SideMenu'
export { default as Modal } from './Modal'
export { default as ArticleLayoutCards } from './BlockItemCards'
export { default as Button } from './Button'
export { default as PageBlock } from './NewPageBlock'
export { default as BlurredImagem } from './ImageBlur'
export { default as T3070Variation } from './NewPageBlock/templates/variations/3070'
export { default as TopBar } from './TopBar'
export { default as Link } from './Link'
// export { default as TemplateSeventyThirtyWithCarousel } from './NewPageBlock/templates/TemplateSeventyThirtyWithCarousel'
export { default as LazyImage } from './LazyImage'
// export { default as T7030WithinNewsletter } from './NewPageBlock/templates/variations/T7030WithinNewsletter'
export { default as Article } from './Article'
export { default as Author } from './Article/Author'
export { default as Body } from './Article/Body'
export { default as Share } from './Article/Share'
export { default as Subtitle } from './Article/Subtitle'
export { default as Title } from './Article/Title'
export { default as Slot100FeaturedRelated } from './NewPageBlock/templates/TemplateSlot100-FeaturedRelated'
export { default as Template5050Grid } from './NewPageBlock/templates/Template5050Grid'

// theme
export * from '../styles/deliveryThemeFunc'
// types
export * from './Article/types'

// icons and types
export * from '../../public/icons/types'
export { default as WhatsappIcon } from '../../public/icons/Whats'
export { default as XIcon } from '../../public/icons/x'
export { default as LinkedinIcon } from '../../public/icons/Linkedin'
export { default as CopyIcon } from '../../public/icons/Copy'
