name: Publish package on NPM from QA Branch

on:
  push:
    branches:
      - qa
  release:
    types: [created]
    branches:
      - qa

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org/'
      - run: yarn
      - run: yarn build
      - run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.UMBRIEL_NPM_TOKEN }}